### ISSUE TITLE
Realization of the knowledge review

### ISSUE THREAD

**Issue by littletomatodonkey** [dvlab-research/ReviewKD#2]
Hi, thanks for your great job! I wrote a kr version using paddle, could you please help see is there any problems? thank you!

https://github.com/littletomatodonkey/code_scipts/blob/main/knowledge_review/knowledge_review.py

I used `conv_1x1` for all the channel transform and `adaptative avg pool` for the size transform.

**Comment by akuxcw** [comment]
Hi, thank you for being interested in our work. The training code is released. We use 1x1 and 3x3 conv for channel trans, and use nearest interpolation and avg pooling for size trans.

**Comment by littletomatodonkey** [comment]
ok, thanks for your remind~
